### ISSUE TITLE
test requirements not documented

### ISSUE THREAD

**Issue by ddriddle** [testing-cabal/extras#3]
When trying to run the unit tests I received the following error: 
```
make check
PYTHONPATH=/home/ddriddle/src/extras python -m testtools.run extras.tests.test_suite
/services/scratch/ddriddle/src/extras/venv/bin/python: No module named testtools
make: *** [check] Error 1
```
This is because extras requires that `testtools` be installed to run the unit tests. This is not documented. Many python projects have a `dev-requirements.txt` file to document the required testing software. I would ask that you add a `dev-requriements.txt` file.

**Comment by rbtcollins** [comment]
I think adding an extras:{'test': ['testtools']} to setup.py is better here, as thats going to follow the sdist around in a way that dev-requirements don't.

**Comment by ddriddle** [comment]
Does it not make more sense to add the testing requirement to to `test_require` instead of to extras? I made a pull request #4 that updates test_require and adds a wrapper class to run the unit tests via testtools.

**Comment by rbtcollins** [comment]
It does yes, because test_require isn't as easily introspectable , and test_require uses easy_install, which is problematic in many environments. Anyhow, it is now documented via tox / .travis.yml; further improvements - e.g. switching to delcarative form via pbr setup.cfg, would be great but aren't needed to close the issue IMO.
